server:
  port: 8501  # Puerto de este microservicio

spring:
  application:
    # Nombre con el que se registrar? en Eureka
    name: reservas

  datasource:
    url: jdbc:mysql://localhost:3306/reservasProyecto?useSSL=false&serverTimezone=UTC
    username: root
    password: abc123.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Valida la estructura, no crea ni modifica
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    prefer-ip-address: true

# Actuator (opcional)
management:
  endpoints:
    web:
      exposure:
        include: "*"
