server:
  port: 8500

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # Este servidor NO se registra a s? mismo
    fetch-registry: false        # No necesita obtener el registro de otros
  server:
    enable-self-preservation: false  # Para evitar problemas en entornos de desarrollo
