server:
  port: 8500

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Este servidor NO se registra a s? mismo
    fetch-registry: false        # No necesita obtener el registro de otros
  server:
    enable-self-preservation: false  # Para evitar problemas en entornos de desarrollo
    peer-eureka-nodes: http://localhost:8500/eureka/  # evita que busque en 8761
