server:
  port: 8500

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Este servidor NO se registra a s? mismo
    fetch-registry: false        # No necesita obtener el registro de otros
  server:
    enable-self-preservation: false  # Para evitar problemas en entornos de desarrollo
    peer-eureka-nodes: ""  # <- esto sí desactiva los peers, indicando que no hay ninguno (cadena vacía) es válida y elimina el intento de replicación al puerto 8761.
